### ISSUE TITLE
pair opening space directly after inserting a pair like newline?  [Feature request/pointers?]

### ISSUE THREAD

**Issue by aufflick** [joaotavora/autopair#47]
Hi, thanks for autpair - still works better/more reliably than electric-pair in my experience :)

Hoping for pointers of how to achieve the following (if it's not currently possible, any pointers as to what elisp funs I should be looking into for where to patch?)

Right after inserting eg. a () pair, I'd like a space to insert a pair of spaces - sort of like currently happens with newlines. Eg. sometimes you want to type `function(arg)` but sometimes that's not very readable and you want to type `complex_func_name( lots, of, spaced, args )`. Once I've achieved this then the ignore whitespace option makes the closing ) easy.

Any thoughts?

**Comment by capitaomorte** [comment]
> Hi, thanks for autpair - still works better/more reliably than electric-pair in my experience :)

Really? Can you describe a concrete situation or two? I did both (autopair and `electric-pair-mode` in Emacs >= 24.4), and in `electric-pair-mode` I tried to make it better in every way, perhaps I missed something then...

> Right after inserting eg. a () pair, I'd like a space to insert a pair of spaces 

OK. If I catch your drift, you want something that is independent of autopair and that is: whenever "point" (the cursor) is between two matching parenthesis, `SPC` inserts not one but two spaces.

If that is the case, then I think using `post-self-insert-hook` is in order. Put this in your `.emacs`

```lisp
(add-hook 'post-self-insert-hook
          'aufflick/add-two-spaces-when-between-matching-parens)

(defun aufflick/add-two-spaces-when-between-matching-parens ()
  (when (and (eq ?\s
                 last-command-event)
             (let* ((here (point))
                    (backthen (- (point) 2))
                    (syntax-after (syntax-after here))
                    (syntax-before (syntax-after backthen)))
               (and (eq (syntax-class (string-to-syntax "(")) (syntax-class syntax-before))
                    (eq (syntax-class (string-to-syntax ")")) (syntax-class syntax-after))
                    (eq (cdr syntax-before) (char-after here))
                    (eq (cdr syntax-after) (char-after backthen)))))
    (self-insert-command 1)
    (backward-char 1)))
```
